openapi: 3.0.1
info:
  title: COVID-19 REST API
  description: "# Descripción\nConsulta todos los datos sobre el COVID-19 en España.\n "
  termsOfService: http://swagger.io/terms/
  contact:
    name: Fran Rivera
    url: https://fran-rivera.github.io/COVID-19-Spain
    email: frgar86@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://covid-spain-api.herokuapp.com/
tags:
- name: Info Covid CCAA
  description: Datos del COVID-19 agrupados por CCAA
  externalDocs:
    description: Datos obtenidos del Ministerio de Sanidad
    url: https://covid19.isciii.es/
paths:
  /info/:
    get:
      tags:
      - Info Covid CCAA
      summary: Info de todos los días de todas las CCAA
      description: Obtén los datos de todas las CCAA desde el inicio de la pandemia
      operationId: findAll
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InfoCovid'
        404:
          description: Not found
          content: {}
        405:
          description: Validation exception
          content: {}
  /info/ccaa:
    get:
      tags:
      - Info Covid CCAA
      summary: Datos de todos los dias de una CCAA
      description: Obtén los datos de una CCAA desde el inicio de la pandemia
      operationId: findByCCAA
      parameters:
      - name: codigo
        in: query
        description: Código ISO 3166-2 de la CCAA para filtrar los resultados
        required: true
        style: form
        explode: true
        schema:
          type: string
          default: AN
          enum:
            - AN
            - AR
            - AS
            - IB
            - CN
            - CB
            - CM
            - CL
            - CT
            - CE
            - VC
            - EX
            - GA
            - MD
            - ML
            - MC
            - NC
            - PV
            - RI
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InfoCovid'
        400:
          description: Invalid codigo value
          content: {}
        404:
          description: Not found
          content: {}
        405:
          description: Validation exception
          content: {}
  /info/date:
    get:
      tags:
      - Info Covid CCAA
      summary: Datos de un solo día de todas las CCAA
      description: Obtén los datos de una fecha concreta de todas las CCAA
      operationId: getInfoCovidByDate
      parameters:
      - name: fecha
        description: Formato dd/MM/yyyy
        in: query
        required: true
        schema:
          type: string
          format: date
      responses:
        "200":
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/InfoCovid'
        400:
          description: Invalid codigo value
          content: {}
        404:
          description: Not found
          content: {}
        405:
          description: Validation exception
          content: {}
  /info/ccaa&date:
    get:
      tags:
      - Info Covid CCAA
      summary: Datos de un solo día de una CCAA
      description: Obtén los datos de una fecha y una CCAA concreta
      operationId: getInfoCovidByDateAndCcaa
      parameters:
      - name: fecha
        description: Formato dd/MM/yyyy
        in: query
        required: true
        schema:
          type: string
          format: date
      - name: codigo
        in: query
        required: true
        schema:
          type: string
          enum:
          - AN
          - AR
          - AS
          - IB
          - CN
          - CB
          - CM
          - CL
          - CT
          - CE
          - VC
          - EX
          - GA
          - MD
          - ML
          - MC
          - NC
          - PV
          - RI
      responses:
        "200":
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/InfoCovid'
        400:
          description: Invalid codigo value
          content: {}
        404:
          description: Not found
          content: {}
        405:
          description: Validation exception
          content: {}
components:
  schemas:
    DataCovid:
      required:
      - fecha
      - region
      type: object
      properties:
        id:
          type: integer
          format: int64
        region:
          type: string
        fecha:
          type: string
          format: date
          description: formato dd/MM/yyyy
          example: 20/03/2020
        hospitalizados:
          type: integer
          format: int32
        fallecidos:
          type: integer
          format: int32
        pcr:
          type: integer
          format: int32
        casos:
          type: integer
          format: int32
        testAc:
          type: integer
          format: int32
        uci:
          type: integer
          format: int32
        recuperados:
          type: integer
          format: int32
    InfoCovid:
      type: object
      properties:
        info:
          type: string
        totalCasos:
          type: integer
          format: int32
        totalHospitalizados:
          type: integer
          format: int32
        totalUCI:
          type: integer
          format: int32
        totalPCR:
          type: integer
          format: int32
        totalTest:
          type: integer
          format: int32
        totalRecuperados:
          type: integer
          format: int32
        totalFallecidos:
          type: integer
          format: int32
        regions:
          type: array
          items:
            $ref: '#/components/schemas/DataCovid'
