---
swagger: '2.0'
info:
  version: '1.0'
  title: REST APIs COVID-19 Spain
  license:
    name: Apache License Version 2.0
host: localhost:8080
basePath: "/"
tags:
- name: data-covid-controller
  description: Get Info Covid-19 Spain
paths:
  "/":
    get:
      tags:
      - data-covid-controller
      summary: wInfoCovid
      operationId: wInfoCovidUsingGET
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  "/addData":
    post:
      tags:
      - data-covid-controller
      summary: addData
      operationId: addDataUsingPOST
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - in: body
        name: dataCovid
        description: dataCovid
        required: true
        schema:
          type: array
          items:
            "$ref": "#/definitions/DataCovid"
      responses:
        '200':
          description: OK
          schema:
            type: string
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  "/ccaa":
    get:
      tags:
      - data-covid-controller
      summary: Datos de todos los dias de una CCAA
      operationId: getInfoCovidByCcaaUsingGET
      produces:
      - "*/*"
      parameters:
      - name: codigo
        in: query
        description: codigo
        required: true
        type: string
        enum:
        - AN
        - AR
        - AS
        - IB
        - CN
        - CB
        - CM
        - CL
        - CT
        - CE
        - VC
        - EX
        - GA
        - MD
        - ML
        - MC
        - NC
        - PV
        - RI
      responses:
        '200':
          description: Suceess|OK
          schema:
            "$ref": "#/definitions/Iterable"
        '401':
          description: Not authorized!
        '403':
          description: Forbidden!!!
        '404':
          description: Not found!!!
      deprecated: false
  "/ccaa&date":
    get:
      tags:
      - data-covid-controller
      summary: Datos de un solo día de una CCAA
      description: Formato de la fecha dd/MM/yyyy
      operationId: getInfoCovidByDateAndCcaaUsingGET
      produces:
      - "*/*"
      parameters:
      - name: codigo
        in: query
        description: codigo
        required: true
        type: string
        enum:
        - AN
        - AR
        - AS
        - IB
        - CN
        - CB
        - CM
        - CL
        - CT
        - CE
        - VC
        - EX
        - GA
        - MD
        - ML
        - MC
        - NC
        - PV
        - RI
      - name: fecha
        in: query
        description: fecha
        required: true
        type: string
        format: date
      responses:
        '200':
          description: Suceess|OK
          schema:
            "$ref": "#/definitions/Iterable"
        '401':
          description: Not authorized!
        '403':
          description: Forbidden!!!
        '404':
          description: Not found!!!
      deprecated: false
  "/date":
    get:
      tags:
      - data-covid-controller
      summary: Datos de un solo día de todas CCAA
      description: Formato de la fecha dd/MM/yyyy
      operationId: getInfoCovidByDateUsingGET
      produces:
      - "*/*"
      parameters:
      - name: fecha
        in: query
        description: fecha
        required: true
        type: string
        format: date
      responses:
        '200':
          description: Suceess|OK
          schema:
            "$ref": "#/definitions/Iterable"
        '401':
          description: Not authorized!
        '403':
          description: Forbidden!!!
        '404':
          description: Not found!!!
      deprecated: false
  "/es":
    get:
      tags:
      - data-covid-controller
      summary: Datos de todos los días de todas las CCAA
      operationId: getInfoCovidUsingGET
      produces:
      - "*/*"
      responses:
        '200':
          description: Suceess|OK
          schema:
            "$ref": "#/definitions/Iterable"
        '401':
          description: Not authorized!
        '403':
          description: Forbidden!!!
        '404':
          description: Not found!!!
      deprecated: false
definitions:
  DataCovid:
    type: object
    properties:
      casos:
        type: integer
        format: int32
      fallecidos:
        type: integer
        format: int32
      fecha:
        type: string
        format: date
      hospitalizados:
        type: integer
        format: int32
      id:
        type: integer
        format: int64
      pcr:
        type: integer
        format: int32
      recuperados:
        type: integer
        format: int32
      region:
        type: string
      testAc:
        type: integer
        format: int32
      uci:
        type: integer
        format: int32
    title: DataCovid
  InfoCovid:
    type: object
    properties:
      info:
        type: string
      regions:
        type: array
        items:
          "$ref": "#/definitions/DataCovid"
      totalCasos:
        type: integer
        format: int32
      totalFallecidos:
        type: integer
        format: int32
      totalHospitalizados:
        type: integer
        format: int32
      totalPCR:
        type: integer
        format: int32
      totalRecuperados:
        type: integer
        format: int32
      totalTest:
        type: integer
        format: int32
      totalUCI:
        type: integer
        format: int32
    title: InfoCovid
  Iterable:
    type: object
    title: Iterable
